# Generated by Django 6.1 on 2026-08-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=48, unique=True)),
                ("slug", models.CharField(max_length=48, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DamageClass",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=8, unique=True)),
                ("slug", models.SlugField(max_length=8, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "damage_class",
            },
        ),
        migrations.CreateModel(
            name="Effect",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("slug", models.CharField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("slug", models.SlugField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=37, unique=True)),
                ("slug", models.SlugField(max_length=37, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=12, unique=True)),
                ("slug", models.CharField(max_length=12, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=8, unique=True)),
                ("slug", models.SlugField(max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.area"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("slug", models.SlugField(max_length=16, unique=True)),
                ("effect", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.generation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.location"
            ),
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("accuracy", models.PositiveSmallIntegerField(null=True)),
                ("power", models.PositiveSmallIntegerField(null=True)),
                ("description", models.TextField()),
                ("effect_chance", models.PositiveSmallIntegerField(null=True)),
                ("pp", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "damage_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.damageclass"
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.effect"
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.generation"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.type"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("sprite", models.ImageField(upload_to="sprites/")),
                ("artwork", models.ImageField(upload_to="official-artwork/")),
                ("name", models.CharField(max_length=15, unique=True)),
                ("slug", models.SlugField(max_length=16, unique=True)),
                ("hp", models.PositiveSmallIntegerField()),
                ("attack", models.PositiveSmallIntegerField()),
                ("defense", models.PositiveSmallIntegerField()),
                ("special_attack", models.PositiveSmallIntegerField()),
                ("special_defense", models.PositiveSmallIntegerField()),
                ("speed", models.PositiveSmallIntegerField()),
                ("height", models.DecimalField(decimal_places=1, max_digits=3)),
                ("weight", models.DecimalField(decimal_places=1, max_digits=4)),
                ("description", models.TextField()),
                ("legendary", models.BooleanField(default=False)),
                ("mythical", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("areas", models.ManyToManyField(through="core.Encounter", to="core.area")),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.generation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="encounter",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.pokemon"
            ),
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.ability"
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.pokemon"
                    ),
                ),
            ],
            options={
                "db_table": "pokemon_abilities",
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(through="core.PokemonAbility", to="core.ability"),
        ),
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "move",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.move"),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.pokemon"
                    ),
                ),
            ],
            options={
                "db_table": "pokemon_moves",
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="moves",
            field=models.ManyToManyField(through="core.PokemonMove", to="core.move"),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=6, unique=True)),
                ("slug", models.SlugField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.generation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="core.region"),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.species"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="type_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="primary_type",
                related_query_name="primary_type",
                to="core.type",
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="type_2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="secondary_type",
                related_query_name="secondary_type",
                to="core.type",
            ),
        ),
    ]
